name             'opsworks_resque'
maintainer       'Pedro Axelrud'
maintainer_email 'pedroaxl@gmail.com'
license          'All rights reserved'
description      'Installs/Configures resque on amazon opsworks'
version          '0.1.0'
