name             'opsworks_redis'
maintainer       'Omar Ramos'
maintainer_email 'omar@digitaltree.com'
license          'All rights reserved'
description      'Configures redis'
version          '0.1.0'
